FROM debian:trixie-slim

RUN apt-get update && apt-get install -y gcc-14 make

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100

WORKDIR /httpd

COPY ./ /httpd/

RUN make

EXPOSE 17701

CMD  ["./build/http_server", "17701"]