FROM alpine:3.21 AS builder

RUN apk add gcc make musl-dev

WORKDIR /httpd

COPY ./ /httpd/

RUN make

FROM alpine:3.21

WORKDIR /httpd

COPY --from=builder /httpd/ .

EXPOSE 17701

CMD  ["./build/http_server", "17701"]